name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "build-tools;33.0.0"
          chmod +x gradlew

      - run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4  # Version v4 au lieu de v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk