name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          licenses: accept

      - name: Install Gradle Directly
        run: |
          # Installe Gradle via le package manager
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle --version

      - name: Clean Project
        run: |
          # Nettoyage complet
          rm -rf .gradle
          rm -rf build

      - name: Build with Gradle
        run: |
          gradle assembleDebug --stacktrace --info
          ls app/build/outputs/apk/debug/

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk