name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          licenses: accept
          api-level: 33
          build-tools: 33.0.0

      - name: Install Gradle Directly
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle --version

      - name: Build with Gradle
        run: |
          gradle assembleDebug --stacktrace \
            --init-script gradle-init.gradle \
            -Dorg.gradle.daemon=false

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk