name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Accept Android Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses > /dev/null
          echo "Licenses accepted"

      - name: Install Android SDK
        run: |
          sdkmanager "platforms;android-33" "build-tools;33.0.0"
          sdkmanager --update

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk