name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android Tools
        uses: android-actions/setup-android@v3
        with:
          licenses: 'android-sdk-license'
          api-level: 33
          build-tools: 33.0.0
          ndk: none
          cmake: none

      - name: Build with Gradle
        run: |
          # Force clean environment
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk