name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          licenses: 'android-sdk-license'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fix Gradle Wrapper
        run: |
          # Régénère complètement les fichiers Gradle
          rm -f gradlew gradlew.bat
          rm -rf gradle/wrapper
          ./gradlew wrapper --gradle-version 8.0 --distribution-type bin
          chmod +x gradlew

      - name: Build APK
        run: |
          ./gradlew assembleDebug --stacktrace --info

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk