name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Android with Docker
        uses: docker://ghcr.io/marketplace/actions/android-emulator-runner:latest
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: nexus6
          script: |
            # Installation directe de Gradle via SDKMAN
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.0
            
            # Build avec Gradle installé globalement
            gradle assembleDebug --stacktrace --info
            
            # Copie de l'APK
            mkdir -p artifacts
            cp app/build/outputs/apk/debug/app-debug.apk artifacts/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: artifacts/app-debug.apk